version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'flask8080'
    working_dir: '/root/src'
    ports:
     - "8080:8080"
    tty: true
    volumes:
      - ./src:/root/src
